name: Deploy static content to Pages

on:
  push:
    branches: ["master"] # Измените на "main", если ваша главная ветка называется main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Используем стабильную Node.js 22 для быстрой сборки Webpack 5
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        # Передаем переменную NODE_ENV=production, чтобы сработал publicPath в конфиге Webpack
        run: NODE_ENV=production npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Укажите ту папку, которую вы посмотрели в Шаге 1 в webpack.config.js (обычно './build')
          path: './build'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
